# Generated by Django 2.0.2 on 2019-06-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=31)),
                ('state', models.CharField(max_length=31)),
                ('pincode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=31)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('duration', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('dept_code', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=31)),
                ('semester', models.CharField(max_length=31)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('theory_prac', models.CharField(max_length=31)),
                ('isRemedial', models.CharField(max_length=31)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyIncharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=31)),
                ('max_marks', models.CharField(max_length=31)),
                ('duration', models.CharField(max_length=31)),
                ('date_of_exam', models.DateField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=31)),
                ('email', models.EmailField(max_length=31)),
                ('password', models.CharField(max_length=31)),
                ('first_name', models.CharField(max_length=31)),
                ('last_name', models.CharField(max_length=31)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_theory', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SessPrac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessTheory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('semester', models.CharField(max_length=31)),
                ('credits', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Course')),
                ('session', models.ManyToManyField(to='Profiler.Session')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=31)),
                ('seq_no', models.CharField(max_length=31)),
                ('start_time', models.DateField()),
                ('location', models.CharField(max_length=31)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Division')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Session')),
            ],
        ),
        migrations.CreateModel(
            name='ToBeCovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Subject')),
                ('to_be_covered', models.ManyToManyField(to='Profiler.ToBeCovered')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiler.Person')),
                ('designation', models.CharField(max_length=31)),
                ('qualification', models.CharField(max_length=31)),
            ],
            bases=('Profiler.person',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Profiler.Person')),
                ('roll_no', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('admission_type', models.CharField(max_length=31)),
                ('is_d2d', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=31)),
                ('cast_category', models.CharField(max_length=31)),
                ('nationality', models.CharField(max_length=31)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('A+', 'A+')], default='A', max_length=31)),
                ('guardian_name', models.CharField(max_length=31)),
                ('guardian_relation', models.CharField(max_length=31)),
            ],
            bases=('Profiler.person',),
        ),
        migrations.AddField(
            model_name='timetable',
            name='to_be_covered',
            field=models.ManyToManyField(to='Profiler.ToBeCovered'),
        ),
        migrations.AddField(
            model_name='person',
            name='Dep_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='Profiler.Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Profiler.Address'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Subject'),
        ),
        migrations.AddField(
            model_name='facultyincharge',
            name='subject',
            field=models.ManyToManyField(to='Profiler.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Person_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Profiler.Person'),
        ),
        migrations.AddField(
            model_name='batch',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.Division'),
        ),
        migrations.AddField(
            model_name='batch',
            name='sess_prac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiler.SessPrac'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.TimeTable'),
        ),
        migrations.AddField(
            model_name='sesstheory',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Faculty'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student'),
        ),
        migrations.AddField(
            model_name='facultyincharge',
            name='faculty',
            field=models.ManyToManyField(to='Profiler.Faculty'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiler.Student'),
        ),
    ]
