# Generated by Django 2.0.2 on 2019-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiler', '0002_auto_20190604_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='isRemedial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='max_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=31),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat')], max_length=31),
        ),
    ]
